language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script: python manage.py test
services:
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create user deploy with superuser;' -U postgres
  - sleep 10
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.0.deb && sudo service elasticsearch restart
