language: python
python:
  - "3.4"
sudo: false
addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch
cache:
  bundler
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - elasticsearch -d --default.path.conf=imageledger/tests/elasticsearch
  - sleep 15
  - python manage.py test
services:
  - postgresql
before_script:
  - psql -c 'create user deploy with superuser;' -U postgres
